// seed-landing.cjs — 랜딩 페이지 데이터 시드
const { Pool } = require('pg');

const DB = 'postgresql://neondb_owner:npg_i0WIuEK3jtvd@ep-proud-shadow-ae72irn5-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require';
const pool = new Pool({ connectionString: DB });

function uid() {
  return Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
}

function daysAgo(n) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

// ─── 20개 매물 ─────────────────────────────────────────────
const listings = [
  // 중고차
  {
    title: '2021 토요타 캠리 SE — 깨끗한 차 급처분',
    description: '5만 마일 미만, 사고 무. 회사 이직으로 차 두 대 유지 어려워 급처분합니다. 내부 깨끗하고 타이어 새것. 직거래 환영, 가격 조금 네고 가능. Plano 거주.',
    price: 22500,
    price_type: 'negotiable',
    category: '자동차',
    condition: '양호',
    contact_method: 'phone',
    contact_info: '469-555-0101',
    author_name: '김민준',
    author_phone: '469-555-0101',
    location: 'Plano, TX',
    city: 'Plano',
    views: 87,
  },
  {
    title: '2019 현대 소나타 SEL — 개인 직거래',
    description: '7만 마일, 풀옵션. 선루프, 가죽시트, 후방카메라 전부 됩니다. 블루링크 앱 연동. 여름에 한국 들어가서 팝니다. 딜러 사절, 개인 직거래만.',
    price: 16800,
    price_type: 'fixed',
    category: '자동차',
    condition: '양호',
    contact_method: 'phone',
    contact_info: '972-555-0202',
    author_name: '이수진',
    author_phone: '972-555-0202',
    location: 'Frisco, TX',
    city: 'Frisco',
    views: 134,
  },
  {
    title: '2022 테슬라 모델 3 스탠다드 레인지 — 세금환급 맞춰 팝니다',
    description: '2만 8천 마일, 화이트 외관/블랙 인테리어. FSD 없음. 충전 비용 절감 크게 느낍니다. Autopilot 기본 포함. 직거래 or 딜러 바이아웃 고려 가능. Coppell 거주.',
    price: 28900,
    price_type: 'negotiable',
    category: '자동차',
    condition: '상',
    contact_method: 'text',
    contact_info: '214-555-0303',
    author_name: '박준혁',
    author_phone: '214-555-0303',
    location: 'Coppell, TX',
    city: 'Dallas',
    views: 221,
  },
  {
    title: '2020 기아 텔루라이드 EX AWD — 7인승 패밀리카',
    description: '6만 마일, 제2열 가죽시트, 파노라마 선루프, 어댑티브 크루즈. 아이들 크면서 미니밴 구입해서 팝니다. 차 상태 매우 깨끗, 스크래치 없음.',
    price: 32000,
    price_type: 'negotiable',
    category: '자동차',
    condition: '상',
    contact_method: 'phone',
    contact_info: '817-555-0404',
    author_name: '최영희',
    author_phone: '817-555-0404',
    location: 'Irving, TX',
    city: 'Irving',
    views: 178,
  },
  // 가구/가전
  {
    title: 'LG 드럼세탁기+건조기 세트 — 이사 급처분',
    description: '2023년 구매, 사용 1년 3개월. 세탁기 5.0cu ft, 건조기 7.3cu ft. 둘 다 흰색 프론트로드. 이사가면서 새집에 이미 있어서 팝니다. 픽업 가능한 분만.',
    price: 1100,
    price_type: 'negotiable',
    category: '가전제품',
    condition: '상',
    contact_method: 'text',
    contact_info: '972-555-0505',
    author_name: '정다은',
    author_phone: '972-555-0505',
    location: 'Richardson, TX',
    city: 'Richardson',
    views: 95,
  },
  {
    title: '삼성 QLED 65인치 4K TV (2022) — 벽걸이 브라켓 포함',
    description: 'QN65Q80B 모델. 리모컨, 원커넥트 박스 포함. 게임모드 120Hz. 화면 완벽, 기스 없음. 벽걸이 브라켓(MSRP $80) 같이 드립니다. Allen 직거래.',
    price: 680,
    price_type: 'fixed',
    category: '가전제품',
    condition: '상',
    contact_method: 'phone',
    contact_info: '469-555-0606',
    author_name: '한동현',
    author_phone: '469-555-0606',
    location: 'Allen, TX',
    city: 'Allen',
    views: 63,
  },
  {
    title: '퀸 매트리스+프레임 세트 — Casper Wave Hybrid',
    description: '2년 사용. 커버 세탁해서 깨끗합니다. 메모리폼+스프링 하이브리드라 허리 좋아요. 프레임은 조립식 금속 프레임 포함. 픽업 직접 가능하거나 소형 트럭 있으신 분.',
    price: 450,
    price_type: 'negotiable',
    category: '가구',
    condition: '양호',
    contact_method: 'text',
    contact_info: '214-555-0707',
    author_name: '송미래',
    author_phone: '214-555-0707',
    location: 'Garland, TX',
    city: 'Garland',
    views: 41,
  },
  {
    title: '식탁+의자 6개 세트 — 원목 우드 모던 스타일',
    description: 'IKEA EKEDALEN 확장형 테이블(120→180cm) + 의자 6개. 4년 사용했지만 관리 잘 했습니다. 흠집 거의 없음. Lewisville 직거래, 분리해서 운반 가능합니다.',
    price: 320,
    price_type: 'negotiable',
    category: '가구',
    condition: '양호',
    contact_method: 'phone',
    contact_info: '972-555-0808',
    author_name: '임혜진',
    author_phone: '972-555-0808',
    location: 'Lewisville, TX',
    city: 'Lewisville',
    views: 29,
  },
  // 전자제품
  {
    title: 'iPhone 15 Pro 256GB 블랙 티타늄 — 언락 직거래',
    description: '6개월 사용. 케이스+필름 항상 부착. 배터리 97%. iCloud 계정 해제 완료. 박스, 케이블 있음(이어폰 없음). AT&T 언락. 케이스 2개 서비스.',
    price: 890,
    price_type: 'fixed',
    category: '전자기기',
    condition: '상',
    contact_method: 'text',
    contact_info: '469-555-0909',
    author_name: '오재원',
    author_phone: '469-555-0909',
    location: 'Plano, TX',
    city: 'Plano',
    views: 112,
  },
  {
    title: 'MacBook Pro 14인치 M3 Pro — 512GB, 회사 지급 반납',
    description: '회사 퇴직 후 구매한 노트북인데 iOS 개발 접고 팝니다. 2024년 1월 구매. 배터리 사이클 42회. 스크래치 전혀 없음. AppleCare 2025년 12월까지. 박스+충전기 포함.',
    price: 1650,
    price_type: 'negotiable',
    category: '전자기기',
    condition: '상',
    contact_method: 'phone',
    contact_info: '214-555-1010',
    author_name: '강지호',
    author_phone: '214-555-1010',
    location: 'Dallas, TX',
    city: 'Dallas',
    views: 198,
  },
  {
    title: 'iPad Air 5세대 Wi-Fi 64GB — 스마트키보드 포함',
    description: '아이 공부용으로 샀는데 결국 안 씁니다. 1년 미만 사용. 화면 기스 없음, 케이스 포함. 스마트키보드(정품, $179짜리) 같이 드립니다. Frisco 직거래.',
    price: 520,
    price_type: 'fixed',
    category: '전자기기',
    condition: '상',
    contact_method: 'text',
    contact_info: '972-555-1111',
    author_name: '윤소희',
    author_phone: '972-555-1111',
    location: 'Frisco, TX',
    city: 'Frisco',
    views: 74,
  },
  // 의류/잡화
  {
    title: '여성 패딩점퍼 / 코트 / 니트 묶음 — 사이즈 S/M',
    description: '한국에서 사온 옷들인데 미국 생활하니 별로 안 입게 됩니다. 유니클로, 자라, 무신사 브랜드 위주. 총 10벌 묶음 판매 (개별 X). 사진 DM 주시면 보내드립니다.',
    price: 150,
    price_type: 'negotiable',
    category: '의류',
    condition: '양호',
    contact_method: 'text',
    contact_info: '469-555-1212',
    author_name: '조연희',
    author_phone: '469-555-1212',
    location: 'McKinney, TX',
    city: 'McKinney',
    views: 38,
  },
  {
    title: '남성 운동화/스니커즈 5켤레 — 270~275mm',
    description: '나이키, 아디다스, 뉴발란스. 전부 깨끗하게 신었고 세탁 완료. 275mm 기준으로 나이키 에어맥스가 약간 크게 나와서 270도 됩니다. 개별/묶음 모두 가능.',
    price: 80,
    price_type: 'negotiable',
    category: '의류',
    condition: '양호',
    contact_method: 'phone',
    contact_info: '817-555-1313',
    author_name: '신태양',
    author_phone: '817-555-1313',
    location: 'Carrollton, TX',
    city: 'Carrollton',
    views: 22,
  },
  // 유아용품
  {
    title: 'Graco 인펀트 카시트 — 뒤보기 신생아용',
    description: 'Graco SnugRide SnugLock 35 Elite. 2023년 10월 구매, 아이 18개월 돼서 컨버터블로 업그레이드합니다. 사고 기록 없음. 커버 세탁 완료. 인서트 포함.',
    price: 95,
    price_type: 'fixed',
    category: '유아용품',
    condition: '상',
    contact_method: 'text',
    contact_info: '214-555-1414',
    author_name: '박소연',
    author_phone: '214-555-1414',
    location: 'Dallas, TX',
    city: 'Dallas',
    views: 56,
  },
  {
    title: 'UPPAbaby VISTA V2 유모차 — 버섯색 그레이',
    description: '2024년 4월 구매. 아이 커서 필요 없어졌습니다. 바구니, 레인커버, 바람막이 전부 있음. 프레임 흠집 거의 없음. 타이어 상태 좋음. Allen 직거래.',
    price: 580,
    price_type: 'negotiable',
    category: '유아용품',
    condition: '상',
    contact_method: 'phone',
    contact_info: '972-555-1515',
    author_name: '이은지',
    author_phone: '972-555-1515',
    location: 'Allen, TX',
    city: 'Allen',
    views: 88,
  },
  {
    title: '아기 침대+매트리스+모빌 세트',
    description: 'IKEA SUNDVIK 원목 아기침대. 매트리스(방수 커버 포함), 범퍼가드, 음악 모빌 같이 드립니다. 2년 사용, 뒤집기 방지 망 포함. 분해해서 드림. Plano 픽업.',
    price: 180,
    price_type: 'negotiable',
    category: '유아용품',
    condition: '양호',
    contact_method: 'text',
    contact_info: '469-555-1616',
    author_name: '김지은',
    author_phone: '469-555-1616',
    location: 'Plano, TX',
    city: 'Plano',
    views: 43,
  },
  // 이사 급매 세트
  {
    title: '【이사 급매】 가전제품 일괄 판매 — 5월 1일 전 픽업 필수',
    description: '한국 귀국으로 전부 처분합니다. LG 냉장고(26cu ft 프렌치도어), 삼성 세탁기, 건조기, 다이슨 청소기(V11), 에어프라이어, 커피머신(델롱기). 일괄 $2,000, 개별 협의. 진짜 급해요.',
    price: 2000,
    price_type: 'negotiable',
    category: '가전제품',
    condition: '양호',
    contact_method: 'phone',
    contact_info: '214-555-1717',
    author_name: '최성훈',
    author_phone: '214-555-1717',
    location: 'Irving, TX',
    city: 'Irving',
    views: 312,
  },
  {
    title: '【이사 급매】 거실/안방 가구 세트 통째로',
    description: '타주 이사 확정. 소파(3인용+1인용), 커피테이블, TV장, 침대프레임(퀸), 화장대, 책상+의자 포함. 전부 3년 이내 구매. 픽업 5월 중순까지. 협의 환영.',
    price: 800,
    price_type: 'negotiable',
    category: '가구',
    condition: '양호',
    contact_method: 'text',
    contact_info: '972-555-1818',
    author_name: '황지영',
    author_phone: '972-555-1818',
    location: 'Carrollton, TX',
    city: 'Carrollton',
    views: 267,
  },
  {
    title: 'Dyson V12 Detect Slim 무선 청소기 — 먼지통 완벽',
    description: '6개월 사용. 이사가면서 새집에 센트럴 진공 있어서 팝니다. 필터 교체 완료. 헤드 3종 포함. 배터리 수명 정상. 박스 없지만 영수증 있음.',
    price: 380,
    price_type: 'fixed',
    category: '가전제품',
    condition: '상',
    contact_method: 'phone',
    contact_info: '469-555-1919',
    author_name: '류민석',
    author_phone: '469-555-1919',
    location: 'Frisco, TX',
    city: 'Frisco',
    views: 91,
  },
  {
    title: '닌텐도 스위치 OLED + 게임 7개 세트',
    description: '2022년 크리스마스 선물로 받았는데 안 하게 됩니다. 마리오카트, 포켓몬 스칼렛, 젤다 포함. 화면 기스 없음, 조이콘 드리프트 없음. 파우치, 충전기 전부 포함.',
    price: 320,
    price_type: 'negotiable',
    category: '전자기기',
    condition: '상',
    contact_method: 'text',
    contact_info: '214-555-2020',
    author_name: '백준서',
    author_phone: '214-555-2020',
    location: 'Richardson, TX',
    city: 'Richardson',
    views: 147,
  },
];

// ─── 10개 커뮤니티 글 ──────────────────────────────────────
const posts = [
  {
    nickname: '달라스새내기',
    title: '달라스 운전면허 필기시험 한국어로 볼 수 있나요?',
    content: '안녕하세요! 지난달에 달라스로 이사 왔는데요, 텍사스 운전면허증 따려고 합니다. 한국에서 면허가 있는데 텍사스에서 인정이 되는지, 아니면 처음부터 시험 봐야 하는지 궁금합니다. DPS에 가면 한국어 필기시험 옵션이 있다고 들었는데 맞나요? 아는 분 계시면 경험 공유 부탁드립니다!',
    category: '생활정보',
    tags: JSON.stringify(['운전면허', 'DPS', '생활정보']),
    views: 89,
    likes: 12,
    comment_count: 7,
    city: 'Dallas',
    created_at: daysAgo(1),
  },
  {
    nickname: '플라노맘',
    title: '플라노 초등학교 등록 어떻게 했어요? (영어 서포트)',
    content: '8살 아이가 있는데 8월에 플라노 ISD로 이사 옵니다. 학교 등록 절차가 궁금하고, 영어를 많이 못하는 아이인데 ESL 프로그램이 어떤지 경험 있으신 분 계세요? 어느 초등학교가 한인 아이들 많은지도 알고 싶습니다. 미리 감사드려요~',
    category: '교육',
    tags: JSON.stringify(['교육', '플라노ISD', '초등학교', 'ESL']),
    views: 134,
    likes: 21,
    comment_count: 15,
    city: 'Plano',
    created_at: daysAgo(1),
  },
  {
    nickname: '넥산보험',
    title: '텍사스 의료보험 — 직장 없을 때 선택지가 뭐가 있나요',
    content: '프리랜서로 일하고 있어서 회사 보험이 없는데요. Healthcare.gov 오바마케어 마켓플레이스랑 Medicaid 중 어떤게 나을까요? 수입이 불규칙한 편이라 메디케이드 자격이 될지도 모르겠고요. 달라스에서 한인 보험 브로커 추천해 주시면 더 좋겠습니다. 경험담 공유 부탁드려요!',
    category: '생활정보',
    tags: JSON.stringify(['의료보험', '보험', '생활정보', '프리랜서']),
    views: 201,
    likes: 34,
    comment_count: 22,
    city: 'Dallas',
    created_at: daysAgo(2),
  },
  {
    nickname: '달라스미식가',
    title: '프리스코/맥키니 쪽 한식 맛집 추천해 주세요',
    content: '프리스코로 이사 온 지 3개월 됐는데 아직 동네 한식당을 잘 모릅니다. 순두부, 삼겹살, 칼국수 잘 하는 곳 혹시 아시나요? 달라스 K-타운까지 안 가고 근처에서 해결하고 싶어서요. 분위기 좋은 한식 레스토랑도 환영입니다. 추천 감사합니다!',
    category: '맛집',
    tags: JSON.stringify(['맛집', '한식', '프리스코', '맥키니']),
    views: 178,
    likes: 45,
    comment_count: 28,
    city: 'Frisco',
    created_at: daysAgo(2),
  },
  {
    nickname: '이삿짐왕초보',
    title: '달라스 내 이사할 때 한인 이삿짐 업체 써보신 분?',
    content: '4월 말에 같은 달라스 내에서 아파트 이사를 해야 합니다. 한국말 되는 이삿짐 업체 있으면 너무 좋겠는데요, 아니더라도 달라스 현지에서 믿을 만한 무빙 업체 추천 부탁드립니다. 2베드룸 이사 비용이 대략 어느 정도 나오는지도 궁금합니다. 경험 있으신 분들 댓글 달아주세요~',
    category: '생활정보',
    tags: JSON.stringify(['이사', '이삿짐', '생활정보']),
    views: 92,
    likes: 8,
    comment_count: 11,
    city: 'Dallas',
    created_at: daysAgo(3),
  },
  {
    nickname: 'IT개발자구직중',
    title: '달라스 IT 취업 어떤가요? 구직 경험 공유해요',
    content: '한국에서 소프트웨어 개발자로 6년 일했고 내년에 달라스로 이민 예정입니다. 달라스/플라노/어빙 쪽에 테크 회사들이 많다고 들었는데, 실제로 취업 시장 어떤지 궁금합니다. H1B 스폰서 해주는 회사 찾기가 어렵나요? LinkedIn 말고 다른 취업 채널도 알려주시면 감사하겠습니다.',
    category: '구인구직',
    tags: JSON.stringify(['취업', 'IT', '개발자', '구직', 'H1B']),
    views: 256,
    likes: 38,
    comment_count: 19,
    city: 'Dallas',
    created_at: daysAgo(3),
  },
  {
    nickname: '한식셰프지망생',
    title: '달라스 한식당 서버/주방 알바 구합니다 (영주권자)',
    content: '영주권자이고 한식당 경험 있습니다. 오전/오후 파트타임 가능하고 주방 보조도 할 수 있어요. 운전 가능하고 달라스 북부 지역(플라노, 앨런, 프리스코) 쪽 선호합니다. 아는 사장님이나 일자리 있으신 분 댓글이나 DM 주세요. 감사합니다.',
    category: '구인구직',
    tags: JSON.stringify(['구인', '알바', '식당', '주방', '서버']),
    views: 67,
    likes: 5,
    comment_count: 4,
    city: 'Plano',
    created_at: daysAgo(4),
  },
  {
    nickname: '달라스봄나들이',
    title: '오늘 화이트록 레이크 다녀왔어요 🌸',
    content: '날씨 너무 좋아서 가족이랑 White Rock Lake 피크닉 다녀왔습니다. 벚꽃은 아니지만 꽃들이 많이 피어 있어서 예쁘더라고요. 달라스 살면서 이런 공원이 있다는 게 진짜 좋아요. 자전거 대여도 가능하고 개 데리고 오는 분들도 많았어요. 날씨 따뜻할 때 한번 가보세요!',
    category: '일상',
    tags: JSON.stringify(['달라스', '나들이', '공원', '일상', '가족']),
    views: 143,
    likes: 52,
    comment_count: 9,
    city: 'Dallas',
    created_at: daysAgo(4),
  },
  {
    nickname: '캐롤튼주부',
    title: 'H마트 vs 한남체인 — 어디가 더 좋아요?',
    content: '캐롤튼에 이사 오고 보니 H마트랑 한남체인이 둘 다 가깝더라고요. 여러분은 어디 주로 가세요? 제 느낌엔 H마트가 신선 야채가 더 자주 들어오는 것 같고, 한남체인은 한국 과자/라면 종류가 더 많은 것 같은데 맞나요? 세일 정보 같은 것도 공유해 주시면 좋겠어요!',
    category: '일상',
    tags: JSON.stringify(['H마트', '한남체인', '마트', '쇼핑', '캐롤튼']),
    views: 221,
    likes: 67,
    comment_count: 34,
    city: 'Carrollton',
    created_at: daysAgo(5),
  },
  {
    nickname: '텍사스신혼부부',
    title: '달라스 아파트 렌트 — 크레딧 없을 때 어떻게 했나요?',
    content: '이민 온 지 6개월 됐는데 아직 미국 크레딧 히스토리가 없습니다. 아파트 렌트할 때 크레딧 없으면 보증금을 2~3달치 더 내야 한다고 하는데, 이 방법 말고 다른 방법 있을까요? 한인 커뮤니티에서 개인 렌트 구하는 게 나을지도 고민 중입니다. 경험 있으신 분 조언 부탁드려요!',
    category: '생활정보',
    tags: JSON.stringify(['아파트', '렌트', '크레딧', '이민', '생활정보']),
    views: 188,
    likes: 29,
    comment_count: 17,
    city: 'Dallas',
    created_at: daysAgo(5),
  },
];

async function seed() {
  console.log('🌱 시드 시작...');

  // listings 삽입
  let listingCount = 0;
  for (const l of listings) {
    const id = 'lst_' + uid();
    await pool.query(
      `INSERT INTO listings (id, title, description, price, price_type, category, condition, photos, contact_method, contact_info, author_name, author_phone, location, status, views, city, created_at, updated_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'active',$14,$15,NOW() - INTERVAL '${Math.floor(Math.random()*14)+1} days',NOW())`,
      [id, l.title, l.description, l.price, l.price_type, l.category, l.condition,
       null, l.contact_method, l.contact_info, l.author_name, l.author_phone,
       l.location, l.views, l.city]
    );
    listingCount++;
    process.stdout.write(`  ✅ 매물 ${listingCount}: ${l.title.slice(0, 30)}...\n`);
  }

  // community_posts 삽입
  let postCount = 0;
  for (const p of posts) {
    const id = 'post_' + uid();
    await pool.query(
      `INSERT INTO community_posts (id, nickname, password_hash, title, content, category, tags, views, likes, comment_count, is_pinned, city, created_at, updated_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,false,$11,$12,NOW())`,
      [id, p.nickname, '$2b$10$dummyhashforseededposts000000000000000000000',
       p.title, p.content, p.category, p.tags,
       p.views, p.likes, p.comment_count, p.city, p.created_at]
    );
    postCount++;
    process.stdout.write(`  ✅ 커뮤니티 ${postCount}: ${p.title.slice(0, 30)}...\n`);
  }

  console.log(`\n🎉 완료! 매물 ${listingCount}개, 커뮤니티 글 ${postCount}개 추가됨`);
  await pool.end();
}

seed().catch(e => { console.error('❌ 오류:', e.message); pool.end(); process.exit(1); });
